---
# tasks file for config_role
- name: Update system packages
  yum:
    name: "*"
    state: latest

- name: Install required system packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - pip
    - git
    - nginx
    - mod_wsgi
  tags: [common_packages]

- name: Clone repo
  git:
    repo: "{{ github_repo }}"
    dest: "{{ full_path }}"
  tags: [clone]

- name: Create virtual Environment
  command:
    python3 -m venv venv
  args:
    chdir: "{{ full_path }}"
  tags: [venv_setup]

- name: Activate virtual environment
  shell:  source venv/bin/activate
  args:
    chdir: "{{ full_path }}"
  tags: [venv_activate]
