---
# tasks file for user_service_role
- name: Install required application dependecies
  become: true
  pip:
    requirements: "{{ full_path }}/{{ app_name_user_service }}/requirements.txt"
  tags: [install_dependencies]
  when: inventory_hostname_in_groups['user_service_servers']

- name: Flask database initialization
  command: flask db init
  args:
    chdir: "{{ full_path }}/{{ app_name_user_service }}"
  tags: [db_init]
  when: inventory_hostname in groups['user_service_servers']

- name: Flask database migration
  command: flask db migrate -m 'Initial migration'
  args:
    chdir: "{{ full_path }}/{{ app_name_user_service }}"
  tags: [db_migrate]
  when: inventory_hostname in groups['user_service_servers']

- name: Flask database upgrade
  command: flask db upgrade
  args:
    chdir: "{{ full_path }}/{{ app_name_user_service }}"
  tags: [db_upgrade]
  when: inventory_hostname in groups['user_service_servers']

- name: Run User microservice
  command: flask run
  args:
    chdir: "{{ full_path }}/{{ app_name_user_service }}"
  tags: [run_user_service]
