---
# - name: Configure Servers
#   hosts: all
#   become: true
#   roles:
#     - common

- name: Deploy application - User
  hosts: user_service_servers
  roles:
    - user_service_role

- name: Deploy application - Product
  hosts: user_service_servers
  roles:
    - product_service_role